// packages/text-area/react/TextAreaComponent.js
import React, { useRef } from "react";
import {
  useAttribute,
  useBooleanAttribute,
  useProperties,
  useEventListener,
} from "./react-utils";
import "../src/index.js";

export function TextAreaComponent({
  children,
  isautofocus,
  isdisabled,
  isreadonly,
  isrequired,
  canresize,
  label,
  textareaid,
  textareaname,
  textarearows,
  textareacols,
  textareaautocomplete,
  labelpartattribute,
  containerpartattribute,
  textareapartattribute,
  formid,
  textareamaxlength,
  textareaminlength,
  textareaplaceholder,
  changehandlername,
  id,
  className,
  style,
  slot,
  on,
  onClick,
}) {
  const ref = useRef(null);

  /** Event listeners */
  useEventListener(ref, "undefined", on);
  useEventListener(ref, "click", onClick);

  /** Boolean attributes */
  useBooleanAttribute(ref, "isAutoFocus", isautofocus);
  useBooleanAttribute(ref, "isDisabled", isdisabled);
  useBooleanAttribute(ref, "isReadOnly", isreadonly);
  useBooleanAttribute(ref, "isRequired", isrequired);
  useBooleanAttribute(ref, "canResize", canresize);

  /** Attributes */
  useAttribute(ref, "label", label);
  useAttribute(ref, "textAreaId", textareaid);
  useAttribute(ref, "textAreaName", textareaname);
  useAttribute(ref, "textAreaRows", textarearows);
  useAttribute(ref, "textAreaCols", textareacols);
  useAttribute(ref, "textAreaAutoComplete", textareaautocomplete);
  useAttribute(ref, "labelPartAttribute", labelpartattribute);
  useAttribute(ref, "containerPartAttribute", containerpartattribute);
  useAttribute(ref, "textAreaPartAttribute", textareapartattribute);
  useAttribute(ref, "formId", formid);
  useAttribute(ref, "textAreaMaxLength", textareamaxlength);
  useAttribute(ref, "textAreaMinLength", textareaminlength);
  useAttribute(ref, "textAreaPlaceHolder", textareaplaceholder);
  useAttribute(ref, "changeHandlerName", changehandlername);
  useAttribute(ref, "id", id);
  useAttribute(ref, "class", className);
  useAttribute(ref, "style", style);
  useAttribute(ref, "slot", slot);

  return React.createElement(
    "ymlwebcl-textarea",
    {
      ref,
      label,
      textAreaId: textareaid,
      textAreaName: textareaname,
      textAreaRows: textarearows,
      textAreaCols: textareacols,
      textAreaAutoComplete: textareaautocomplete,
      labelPartAttribute: labelpartattribute,
      containerPartAttribute: containerpartattribute,
      textAreaPartAttribute: textareapartattribute,
      formId: formid,
      textAreaMaxLength: textareamaxlength,
      textAreaMinLength: textareaminlength,
      textAreaPlaceHolder: textareaplaceholder,
      changeHandlerName: changehandlername,
      id,
      className,
      style,
      slot,
    },
    children
  );
}

// packages/text-area/src/text-area/textArea.component.ts
import { html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { TailwindElement } from '../shared/tailwind.element';
import { AutoComplete } from '../types/text-area';
import { AutoCompleteValues } from '../constants/text-area';

@customElement('ymlwebcl-textarea')
export class TextAreaComponent extends TailwindElement(null) {
  @property({ type: String, reflect: true })
  label?: string = '';
  @property({ type: String, reflect: true })
  textAreaId?: string = '';
  @property({ type: String, reflect: true })
  textAreaName?: string = '';
  @property({ type: Number, reflect: true })
  textAreaRows?: number = 2;
  @property({ type: Number, reflect: true })
  textAreaCols?: number = 20;
  @property({ reflect: true })
  textAreaAutoComplete?: AutoComplete = AutoCompleteValues.Off;
  @property({ type: Boolean, reflect: true })
  isAutoFocus?: boolean = false;
  @property({ type: Boolean, reflect: true })
  isDisabled?: boolean = false;
  @property({ type: String, reflect: true })
  labelPartAttribute?: string = 'webcl-textarea-label';
  @property({ type: String, reflect: true })
  containerPartAttribute?: string = 'webcl-textarea-container';
  @property({ type: String, reflect: true })
  textAreaPartAttribute?: string = 'webcl-textarea';
  @property({ type: String, reflect: true })
  formId?: string = '';
  @property({ type: Number, reflect: true })
  textAreaMaxLength?: number;
  @property({ type: Number, reflect: true })
  textAreaMinLength?: number;
  @property({ type: String, reflect: true })
  textAreaPlaceHolder?: string = '';
  @property({ type: Boolean, reflect: true })
  isReadOnly?: boolean = false;
  @property({ type: Boolean, reflect: true })
  isRequired?: boolean = false;
  @property({ type: String, reflect: true })
  changeHandlerName?: string = '';
  @property({ type: Boolean, reflect: true })
  canResize?: boolean = true;

  protected getTextAreaClassList() {
    const { canResize } = this;
    return canResize ? 'resize' : 'resize-none';
  }

  render() {
    return html`<div part=${this.containerPartAttribute}>
      ${this.label
        ? html`<label
            for=${this.textAreaId}
            part=${this.labelPartAttribute}
            class="flex"
            >${this.label}</label
          >`
        : nothing}
      <textarea
        part=${this.textAreaPartAttribute}
        class=${this.getTextAreaClassList()}
        id=${this.textAreaId}
        name=${this.textAreaName}
        rows=${this.textAreaRows}
        cols=${this.textAreaCols}
        autocomplete=${this.textAreaAutoComplete}
        ?autofocus=${this.isAutoFocus}
        ?disabled=${this.isDisabled}
        ?form=${this.formId}
        maxlength=${this.textAreaMaxLength}
        minlength=${this.textAreaMinLength}
        placeholder=${this.textAreaPlaceHolder}
        ?readonly=${this.isReadOnly}
        ?required=${this.isRequired}
        @input=${({ target: { value } }) =>
          this.dispatchEvent(
            new CustomEvent(this.changeHandlerName, { detail: { value } })
          )}
      ></textarea>
    </div>`;
  }
}
