// packages/avatar/src/avatar/avatar.component.ts
import { html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { TailwindElement } from '../shared/tailwind.element';
import { msg, str } from '@lit/localize';

@customElement('ymlwebcl-avatar')
export class AvatarComponent extends TailwindElement(null) {
  @property({ type: Boolean, reflect: true })
  isRounded?: boolean = false;
  @property({ type: Number, reflect: true })
  width?: number = 75;
  @property({ type: Number, reflect: true })
  height?: number = 75;
  @property({ type: Boolean, reflect: true })
  usePercentage?: boolean = false;
  @property({ type: Boolean, reflect: true })
  hasBorder?: boolean = false;
  @property({ type: String, reflect: true })
  borderColor?: string = 'slate-200';
  @property({ type: String, reflect: true })
  defaultBgColor?: string;
  @property({ type: String, reflect: true })
  slotName?: string;
  @property({ attribute: 'onAvatarClick', reflect: true })
  onAvatarClick?: () => void;
  @property({ type: Boolean, reflect: true })
  hasShadow?: boolean = false;
  @property({ type: Boolean, reflect: true })
  showDefaultIcon?: boolean = false;
  @property({ type: String, reflect: true })
  defaultImage?: string;
  @property()
  avatarPartAttribute?: string = 'webcl-avatar';

  private getContainerClassList() {
    const { isRounded, hasBorder, borderColor, hasShadow, defaultBgColor } =
      this;
    return `webcl-avatar-container flex items-center justify-center ${
      defaultBgColor || ''
    } ${isRounded ? 'rounded-full' : ''} ${
      hasBorder ? `border border-${borderColor}` : ''
    } ${hasShadow ? 'shadow' : ''}`.trim();
  }
  private getContainerDimensions() {
    const { width, height, usePercentage } = this;
    const dimension = `${usePercentage ? '%' : 'px'}`;
    return `width: ${width}${dimension};height: ${height}${dimension};`;
  }

  private renderDefaultIcon() {
    const { defaultImage, showDefaultIcon, width, height } = this;
    return showDefaultIcon
      ? html`<img
          src=${defaultImage}
          alt="default icon"
          width="${width}px"
          height="${height}px"
        />`
      : '';
  }

  render() {
    return html`<div
      class=${this.getContainerClassList()}
      style=${this.getContainerDimensions()}
      part=${this.avatarPartAttribute}
      role=${msg(str`button`)}
      @click=${this.onAvatarClick}
    >
      ${this.renderDefaultIcon()}
      ${this.slotName ? html`<slot name=${this.slotName}></slot>` : ''}
    </div>`;
  }
}

// packages/avatar/react/AvatarComponent.js
import React, { useRef } from "react";
import {
  useAttribute,
  useBooleanAttribute,
  useProperties,
  useEventListener,
} from "./react-utils";
import "../src/index.js";

export function AvatarComponent({
  children,
  isrounded,
  usepercentage,
  hasborder,
  hasshadow,
  showdefaulticon,
  width,
  height,
  bordercolor,
  defaultbgcolor,
  slotname,
  onavatarclick,
  defaultimage,
  avatarpartattribute,
  id,
  className,
  style,
  slot,
  onClick,
}) {
  const ref = useRef(null);

  /** Event listeners */
  useEventListener(ref, "click", onClick);

  /** Boolean attributes */
  useBooleanAttribute(ref, "isRounded", isrounded);
  useBooleanAttribute(ref, "usePercentage", usepercentage);
  useBooleanAttribute(ref, "hasBorder", hasborder);
  useBooleanAttribute(ref, "hasShadow", hasshadow);
  useBooleanAttribute(ref, "showDefaultIcon", showdefaulticon);

  /** Attributes */
  useAttribute(ref, "width", width);
  useAttribute(ref, "height", height);
  useAttribute(ref, "borderColor", bordercolor);
  useAttribute(ref, "defaultBgColor", defaultbgcolor);
  useAttribute(ref, "slotName", slotname);
  useAttribute(ref, "onAvatarClick", onavatarclick);
  useAttribute(ref, "defaultImage", defaultimage);
  useAttribute(ref, "avatarPartAttribute", avatarpartattribute);
  useAttribute(ref, "id", id);
  useAttribute(ref, "class", className);
  useAttribute(ref, "style", style);
  useAttribute(ref, "slot", slot);

  return React.createElement(
    "ymlwebcl-avatar",
    {
      ref,
      width,
      height,
      borderColor: bordercolor,
      defaultBgColor: defaultbgcolor,
      slotName: slotname,
      onAvatarClick: onavatarclick,
      defaultImage: defaultimage,
      avatarPartAttribute: avatarpartattribute,
      id,
      className,
      style,
      slot,
    },
    children
  );
}
